import {
  RiUserLine,
  RiLockLine,
  RiMailLine,
  RiPhoneLine,
  RiEarthLine,
  RiMapPinLine,
} from "react-icons/ri";

export const signInFields = [
  {
    label: "Username",
    name: "username",
    type: "text",
    placeholder: "Enter your username",
    icon: RiUserLine,
    variable: "userName",
  },
  {
    label: "Password",
    name: "password",
    type: "password",
    placeholder: "Enter your password",
    icon: RiLockLine,
    showPasswordToggle: true,
    variable: "password",
  },
];

export const signUpFields = {
  page1: [
    {
      label: "Username",
      name: "username",
      type: "text",
      placeholder: "Enter your username",
      icon: RiUserLine,
      variable: "userName",
    },
    {
      label: "Name",
      name: "name",
      type: "text",
      placeholder: "Enter your name",
      icon: RiUserLine,
      variable: "name",
    },
    {
      label: "Email (Optional)",
      name: "email",
      type: "email",
      placeholder: "Enter your email",
      icon: RiMailLine,
      variable: "email",
      optional: true,
    },
    {
      label: "Password",
      name: "password",
      type: "password",
      placeholder: "Enter your password",
      icon: RiLockLine,
      showPasswordToggle: true,
      variable: "password",
    },
  ],

  page2: [
    {
      id: "gender",
      title: "Gender",
      type: "list",
      placeholder: "Select Gender",
      variable: "gender",
      options: [
        { name: "Male", value: "male" },
        { name: "Female", value: "female" },
        { name: "Other", value: "other" },
      ],
    },
    {
      label: "Phone Number",
      name: "phone",
      type: "tel",
      placeholder: "Enter your phone number",
      icon: RiPhoneLine,
      variable: "phone",
    },
    {
      id: "district",
      title: "District",
      type: "list",
      placeholder: "Select District",
      variable: "district",
      options: [
        { name: "Balaka", value: "Balaka" },
        { name: "Blantyre", value: "Blantyre" },
        { name: "Chikwawa", value: "Chikwawa" },
        { name: "Chiradzulu", value: "Chiradzulu" },
        { name: "Chitipa", value: "Chitipa" },
        { name: "Dedza", value: "Dedza" },
        { name: "Dowa", value: "Dowa" },
        { name: "Karonga", value: "Karonga" },
        { name: "Kasungu", value: "Kasungu" },
        { name: "Likoma", value: "Likoma" },
        { name: "Lilongwe", value: "Lilongwe" },
        { name: "Machinga", value: "Machinga" },
        { name: "Mangochi", value: "Mangochi" },
        { name: "Mchinji", value: "Mchinji" },
        { name: "Mulanje", value: "Mulanje" },
        { name: "Mwanza", value: "Mwanza" },
        { name: "Mzimba", value: "Mzimba" },
        { name: "Neno", value: "Neno" },
        { name: "Nkhata Bay", value: "Nkhata Bay" },
        { name: "Nkhotakota", value: "Nkhotakota" },
        { name: "Nsanje", value: "Nsanje" },
        { name: "Ntcheu", value: "Ntcheu" },
        { name: "Ntchisi", value: "Ntchisi" },
        { name: "Phalombe", value: "Phalombe" },
        { name: "Rumphi", value: "Rumphi" },
        { name: "Salima", value: "Salima" },
        { name: "Thyolo", value: "Thyolo" },
        { name: "Zomba", value: "Zomba" },
      ],
    },
    {
      id: "preferredLanguage",
      title: "Preferred Language",
      type: "list",
      placeholder: "Select Language",
      variable: "preferredLanguage",
      options: [
        { name: "English", value: "en" },
        { name: "Chichewa", value: "ny" },
        { name: "Tumbuka", value: "tum" },
      ],
    },
  ],
};

export const addUserFields = {
  basicInfo: [
    {
      id: "fullName",
      title: "Full Name",
      type: "text",
      placeholder: "John Doe",
      required: true,
      variable: "full_name",
    },
    {
      id: "email",
      title: "Email",
      type: "email",
      placeholder: "yourname@example.com",
      required: true,
      variable: "email",
    },
    {
      id: "role",
      title: "Role",
      type: "list",
      placeholder: "Select Role",
      variable: "role",
      options: [
        { name: "Patient", value: "patient" },
        { name: "Ambulance driver", value: "ambulance_driver" },
        { name: "Nurse", value: "nurse" },
        { name: "Doctor", value: "doctor" },
        { name: "Admin", value: "admin" },
        { name: "HOD", value: "hod" },
      ],
    },
    {
      id: "phoneNumber",
      title: "Phone Number",
      type: "text",
      placeholder: "0888659011",
      required: true,
      variable: "phone_number",
    },
    {
      id: "gender",
      title: "Gender",
      type: "list",
      placeholder: "Select Gender",
      variable: "gender",
      options: [{ name: "male" }, { name: "female" }],
    },
    {
      id: "dateOfBirth",
      title: "Date of Birth",
      type: "date",
      placeholder: "YYYY-MM-DD",
      required: true,
      variable: "dob",
    },
  ],
};
